// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Mutation struct {
}

type Query struct {
}

type Task struct {
	ID         string `json:"id"`
	Message    string `json:"message"`
	BinaryCode string `json:"binaryCode"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
}
