// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: task.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_ReceiveTaskToProcess_FullMethodName = "/task.TaskService/ReceiveTaskToProcess"
	TaskService_SendProcessedTask_FullMethodName    = "/task.TaskService/SendProcessedTask"
	TaskService_GetTasks_FullMethodName             = "/task.TaskService/GetTasks"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	ReceiveTaskToProcess(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReceiveTaskToProcessRequest, ReceiveTaskToProcessResponse], error)
	SendProcessedTask(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendProcessedTaskRequest, SendProcessedTaskResponse], error)
	GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) ReceiveTaskToProcess(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReceiveTaskToProcessRequest, ReceiveTaskToProcessResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskService_ServiceDesc.Streams[0], TaskService_ReceiveTaskToProcess_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReceiveTaskToProcessRequest, ReceiveTaskToProcessResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskService_ReceiveTaskToProcessClient = grpc.ClientStreamingClient[ReceiveTaskToProcessRequest, ReceiveTaskToProcessResponse]

func (c *taskServiceClient) SendProcessedTask(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendProcessedTaskRequest, SendProcessedTaskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskService_ServiceDesc.Streams[1], TaskService_SendProcessedTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendProcessedTaskRequest, SendProcessedTaskResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskService_SendProcessedTaskClient = grpc.ClientStreamingClient[SendProcessedTaskRequest, SendProcessedTaskResponse]

func (c *taskServiceClient) GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_GetTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility.
type TaskServiceServer interface {
	ReceiveTaskToProcess(grpc.ClientStreamingServer[ReceiveTaskToProcessRequest, ReceiveTaskToProcessResponse]) error
	SendProcessedTask(grpc.ClientStreamingServer[SendProcessedTaskRequest, SendProcessedTaskResponse]) error
	GetTasks(context.Context, *GetTasksRequest) (*GetTasksResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) ReceiveTaskToProcess(grpc.ClientStreamingServer[ReceiveTaskToProcessRequest, ReceiveTaskToProcessResponse]) error {
	return status.Error(codes.Unimplemented, "method ReceiveTaskToProcess not implemented")
}
func (UnimplementedTaskServiceServer) SendProcessedTask(grpc.ClientStreamingServer[SendProcessedTaskRequest, SendProcessedTaskResponse]) error {
	return status.Error(codes.Unimplemented, "method SendProcessedTask not implemented")
}
func (UnimplementedTaskServiceServer) GetTasks(context.Context, *GetTasksRequest) (*GetTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTasks not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}
func (UnimplementedTaskServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_ReceiveTaskToProcess_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskServiceServer).ReceiveTaskToProcess(&grpc.GenericServerStream[ReceiveTaskToProcessRequest, ReceiveTaskToProcessResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskService_ReceiveTaskToProcessServer = grpc.ClientStreamingServer[ReceiveTaskToProcessRequest, ReceiveTaskToProcessResponse]

func _TaskService_SendProcessedTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskServiceServer).SendProcessedTask(&grpc.GenericServerStream[SendProcessedTaskRequest, SendProcessedTaskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskService_SendProcessedTaskServer = grpc.ClientStreamingServer[SendProcessedTaskRequest, SendProcessedTaskResponse]

func _TaskService_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTasks(ctx, req.(*GetTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTasks",
			Handler:    _TaskService_GetTasks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveTaskToProcess",
			Handler:       _TaskService_ReceiveTaskToProcess_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SendProcessedTask",
			Handler:       _TaskService_SendProcessedTask_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "task.proto",
}
